/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Common constants for all features.
 */
export class CommonConstants {
  /**
   * Full percent.
   */
  static readonly FULL_PERCENT: string = '100%';
  /**
   * Half percent.
   */
  static readonly HALF_PERCENT: string = '50%';
  /**
   * Device PC/2in1.
   */
  static readonly DEVICE_2IN1: string = '2in1';
  /**
   * Playing state of avPlayer.
   */
  static readonly AV_PLAYER_PLAYING_STATE: string = 'playing';
  /**
   * Initial time.
   */
  static readonly INITIAL_TIME: string = '00:00:00';
  /**
   *  Constant for screen dpi.
   */
  static readonly SCREEN_DPI_CONSTANT: number = 160;
  /**
   * Current time of av player.
   */
  static readonly AV_PLAYER_CURRENT_TIME: string = 'currentTime';
  /**
   * Update time of av player.
   */
  static readonly AV_PLAYER_UPDATE_TIME: string = 'updateTime';
  /**
   * Progress of av player.
   */
  static readonly AV_PLAYER_PROGRESS: string = 'progress';
  /**
   * State of av player.
   */
  static readonly AV_PLAYER_STATE: string = 'avplayerState';
  /**
   * Util of av player.
   */
  static readonly AV_PLAYER_UTIL: string = 'avplayerState';
  /**
   * One hundred for progress.
   */
  static readonly PROGRESS_HUNDRED: number = 100;
  /**
   * Idle state of avPlayer.
   */
  static readonly AV_PLAYER_IDLE_STATE: string = 'idle';
  /**
   * Product video name.
   */
  static readonly PRODUCT_VIDEO_NAME: string = 'product.mp4';
  /**
   * Initialized state of avPlayer.
   */
  static readonly AV_PLAYER_INITIALIZED_STATE: string = 'initialized';
  /**
   * Prepared state of avPlayer.
   */
  static readonly AV_PLAYER_PREPARED_STATE: string = 'prepared';
  /**
   * Total time of av player.
   */
  static readonly AV_PLAYER_TOTAL_TIME: string = 'totalTime';
  /**
   * Pause state of avPlayer.
   */
  static readonly AV_PLAYER_PAUSED_STATE: string = 'paused';
  /**
   * Completed state of avPlayer.
   */
  static readonly AV_PLAYER_COMPLETED_STATE: string = 'completed';
  /**
   * Stopped state of avPlayer.
   */
  static readonly AV_PLAYER_STOPPED_STATE: string = 'stopped';

  /**
   * Release state of avPlayer.
   */
  static readonly AV_PLAYER_RELEASE_STATE: string = 'released';

  /**
   * Error state of avPlayer.
   */
  static readonly AV_PLAYER_ERROR_STATE: string = 'error';
  /**
   * One thousand for progress.
   */
  static readonly PROGRESS_THOUSAND: number = 1000;

  /**
   * Second in hour.
   */
  static readonly SECOND_IN_HOUR: number = 3600;

  /**
   * Second in minute.
   */
  static readonly SECOND_IN_MINUTE: number = 60;
  /**
   * colon.
   */
  static readonly COLON: string = ':';
  /**
   * Time prefix.
   */
  static readonly TIME_PREFIX: string = '0';
  /**
   * Ten.
   */
  static readonly TEN: number = 10;
  /**
   * One.
   */
  static readonly ONE: number = 1;
  /**
   * Zero.
   */
  static readonly ZERO: number = 0;
  /**
   * Empty time.
   */
  static readonly EMPTY_TIME: string = '00';
  /**
   * Break point of width.
   */
  static readonly WIDTH_BREAK_POINT: string = 'widthBp';
  /**
   * Break point of height.
   */
  static readonly HEIGHT_BREAK_POINT: string = 'heightBp';
  /**
   * SurfaceId of detail.
   */
  static readonly DETAIL_SURFACE_ID: string = 'detailSurfaceId';
}